### PR TITLE
Mort/to merge to 2.6.53dev

### PR DESCRIPTION
**Pull request by mohicks**
This is a rebase + some fixes.  It rebases on top of the latest 2.6.52dev instead of the previous base that mcr did most of this development on.

### CODE REVIEW

**Comment by AnatoliChe** [comment]
Sorry for boring, but have you deleted null algos, broke CTR and have not implemented GCM algos?
`002 "peer1-peer2" #7: initiating Quick Mode RSASIG+ENCRYPT+PFS+UP+IKEv2ALLOW+SAREFTRACK {using isakmp#6 msgid:2e12a172 proposal=aes_ctr(13)_160-hmac_sha1_96(2)_160 pfsgroup=OAKLEY_GROUP_MODP1024}`
`003 "peer1-peer2" #7: ESP transform ID of ISAKMP Transform Payload (ESP) has an unknown out value: 0
`
And this version is still bitten by [segfault](https://github.com/xelerance/Openswan/issues/451) which can be invoke remotely with 100% of reproducing?

**Comment by letoams** [comment]
At this point openswan has been abandoned for 10 years. Libreswan is older than openswan was an active fork of freeswan.

Why are you still trying to use this ?

**Comment by shussain** [comment]
> Sorry for boring, but in this version have deleted null algos, broken CTR and have not implemented GCM algos?

Thank you for reporting the issue Anthony. 

> And this version is still bitten by [segfault](https://github.com/xelerance/Openswan/issues/451) which can be invoke remotely with 100% of reproducing?

Thank you for reporting that. Our plan is to investigate and address that this week or next.

**Comment by shussain** [comment]
Thank you for the PR @mohicks 

@AnatoliChe The issues you had reported (deleted null algos, broken CTR, etc) are being investigated and we may followup with you later on with more questions.

**Pull request closed without merging**
